# Generated by Django 4.2.3 on 2024-06-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default="alemfelippe@gamil.com", max_length=100
            ),
        ),
    ]
