# Generated by Django 4.2.3 on 2024-06-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default="alemfelippe@gmail.com", max_length=100
            ),
        ),
    ]
