# Generated by Django 4.2.3 on 2024-05-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_rename_profile_certificate_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="projects/static/img"
            ),
        ),
    ]
